### ISSUE TITLE
Statistics misspelled in page header

### ISSUE THREAD

**Issue by dankessler** [UMichStatistics/ComputingClub#3]
The header for the page currently has a typo in how "Statistics" is spelled. It's not a big deal, but since it's on the header and shows up on every page it'd be nice to fix. 

From grep-ing across the repo, the only places outside of `/docs` (which are build artifacts) where the typo occurs are in [`config.toml`](https://github.com/UMichStatistics/ComputingClub/blob/master/config.toml#L9) and [`config/_default/config.toml`](https://github.com/UMichStatistics/ComputingClub/blob/master/config/_default/config.toml#L9). 

I was able to install Hugo on my machine, but I get tons of warnings when trying to build the site, and if I try to serve it locally I just get essentially empty pages, so although I can fix the `toml` files, I can't fix the website.

@fontaine618 could you fix this and re-build?

**Comment by fontaine618** [comment]
Done!
